### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by pepjo** [yahoo/babel-plugin-react-intl#10] opened 2015-10-18 17:47 UTC
I am not sure what I'm doing wrong, but I cannot get it to work.

I am using gulp and babelify. I have checked that babelify uses the last version of babel-core and I have configure it to load my .babelrc file as follows:
````javascript
bundler.transform(babelify.configure({
  sourceMapRelative: 'app/js',
  babelrc: '../../.babelrc'
}))
````

My .babelrc file contains the following: 
````javascript
{
  "plugins": ["react-intl"],
  "extra": {
    "react-intl": {
      "messagesDir": "./",
      "enforceDescriptions": true
    }
  }
}
````

Do you have an idea of why it's not working?

**Comment by ericf** [comment] 2015-10-24 16:42
Are you using ES6 module `import`s?

**Comment by pepjo** [comment] 2015-10-24 16:53
When I tested this I was not, I'll try again changing that.

Thanks for the replay :smile:

**Comment by ericf** [comment] 2015-10-24 16:54
Closing as duplicate of #6

**Closed by ericf** 2015-10-24 16:54 UTC

**Comment by pepjo** [comment] 2015-10-24 17:52
I post here not on #6 because this is specific for this issue.

A part from not using ES6 to import I was also defining a bad .babelrc. Even thought the relative path to the .babelrc from my gulp task file is `../../.babelrc` for some reason it only works if i use `.babelrc`. I guess it is relative to the project path.

Just saying this to help anyone with the same problem :)

**Comment by pepjo** [comment] 2015-10-24 18:13
Implemented `import` in ES6 and corrected the `.babelrc` problem and still does not work.

I have put some `console.log()`s inside the plugin to see if I could find out what was wrong. It seems that the function `enter` of the `Plugin` gets called one time per each file I have but the function `exit` never gets called. I don't know if this is an expected behavior but I suspect its not.

I'll try running babel alone without babelify or browserify to see if something in my workflow is breaking the plugin. But, do you have any clue why it still does not work?

**Comment by pepjo** [comment] 2015-10-24 18:33
OK, seems to work using a babel directly. I'll create a different gulp task for extracting. This is strange though.
