### ISSUE TITLE
[React Intl] `undefined()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.

### ISSUE THREAD

**Issue by Syntaxe3** [yahoo/babel-plugin-react-intl#172] opened 2019-05-27 13:10 UTC
[https://github.com/formatjs/babel-plugin-react-intl/blob/master/src/index.js#L330](https://github.com/formatjs/babel-plugin-react-intl/blob/master/src/index.js#L330)
With version 3.0.2 I got this syntax error. 3.0.1 is ok

**Comment by znarf** [comment] 2019-05-27 18:26
Breaking here also:
https://github.com/opencollective/opencollective-frontend/pull/1849
https://circleci.com/gh/opencollective/opencollective-frontend/22647

This was supposed to be a patch version.

**Comment by longlho** [comment] 2019-05-28 03:54
dupe of https://github.com/formatjs/formatjs/issues/37 we'll release a new version that fixes this asap

**Closed as completed by longlho** 2019-05-28 03:54 UTC
